version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    environment:
      - "SQLALCHEMY_DATABASE_URI=postgres://klaviyo:password@postgres:5432/klaviyo"
      - "MAILGUN_API_KEY=key-db1e2c1d2894057d14a9234d10213331"
    depends_on:
      - postgres
  postgres:
    container_name: "postgres"
    image: "postgres:9.4"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
